export const ExitCode = {
  DONE: 0,
  COMMAND_ERROR: 1,
  NEEDS_INSTRUCTION: 10,
  NEEDS_PLAN: 11,
  NEEDS_DESIGN_REVIEW: 12,
  DESIGN_APPROVED: 13,
  IMPLEMENTING: 14,
  NEEDS_IMPL_REPORT: 15,
  NEEDS_IMPL_REVIEW: 16,
  REJECTED: 17,
  BROKEN_STATE: 20,
} as const;

export type ExitCodeValue = (typeof ExitCode)[keyof typeof ExitCode];

export const ExitCodeName: Record<ExitCodeValue, string> = {
  [ExitCode.DONE]: 'DONE',
  [ExitCode.COMMAND_ERROR]: 'COMMAND_ERROR',
  [ExitCode.NEEDS_INSTRUCTION]: 'NEEDS_INSTRUCTION',
  [ExitCode.NEEDS_PLAN]: 'NEEDS_PLAN',
  [ExitCode.NEEDS_DESIGN_REVIEW]: 'NEEDS_DESIGN_REVIEW',
  [ExitCode.DESIGN_APPROVED]: 'DESIGN_APPROVED',
  [ExitCode.IMPLEMENTING]: 'IMPLEMENTING',
  [ExitCode.NEEDS_IMPL_REPORT]: 'NEEDS_IMPL_REPORT',
  [ExitCode.NEEDS_IMPL_REVIEW]: 'NEEDS_IMPL_REVIEW',
  [ExitCode.REJECTED]: 'REJECTED',
  [ExitCode.BROKEN_STATE]: 'BROKEN_STATE',
};
